spring:
  profiles:
    active: local
  application:
    name: financial-ledge-backend

server:
  port: 8080

jwt:
  secret: your-secret-key-should-be-at-least-256-bits-long-for-hs256-algorithm-mini-money-secret-key-2024
  expiration: 86400000

logging:
  level:
    root: INFO

